name: Build and deploy

on:
  workflow_call:
    inputs:
      git-branch:
        description: 'Git branch for deployment'
        required: true
        type: string
      deployment-url:
        description: 'URL for deployment'
        required: true
        type: string
      vercel-team-scope:
        description: 'Vercel team scope'
        default: 'asifhafeez89'
        type: string
    secrets:
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID:
        required: true
      VERCEL_TOKEN:
        required: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install
      working-directory: my-next-app

    - name: Install Vercel CLI
      run: npm install --global vercel@latest

    - name: Deploy to Vercel
      run: |
        vercel pull --yes --environment=preview --git-branch=${{ inputs.git-branch }} --token=${{ secrets.VERCEL_TOKEN }} 
        vercel build --token=${{ secrets.VERCEL_TOKEN }} 
        url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})" 
        vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" ${{ inputs.deployment-url }} 
