name: Build and deploy another app

on:
  push:
    branches:
      - main
    paths:
      - 'another-app/**'


jobs:
  deploy-to-test:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      git-branch: 'test'
      deployment-url: 'another-app-bravo-blond.vercel.app'
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.ANOTHER_APP_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  end-to-end-testing:
    needs: deploy-to-test
    runs-on: ubuntu-latest
    steps:
      - name: Running End-to-End Tests
        run: echo "Running tests"
  deploy-to-uat:
    needs: end-to-end-testing
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      git-branch: 'uat'
      deployment-url: 'another-app-charlie-blond.vercel.app'
    secrets:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.ANOTHER_APP_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      